/* Non-canonical prototype data for the OpenWorlds fidelity surface.
   This file is a visual/demo seed only until viewer APIs bind real ClawDnD
   read models. Do not treat it as campaign, world, lore, or rules truth. */

const INITIAL_STATE = {
  activeCampaign: "odrun",
  campaigns: [
    {
      id: "odrun",
      title: "The Long Road to Odrun",
      subtitle: "Chapter II — Of Toll Roads and Quiet Inns",
      system: "Pathfinder 1e",
      chapter: "II",
      lastPlayed: "Tuesday past",
      sessions: 14,
      region: "The Stolen Marches",
      day: "Day 12 · 29 Gozran",
      party: [
        { name: "Cassian", short: "portrait" },
        { name: "Mira", short: "portrait" },
        { name: "Vell", short: "portrait" },
        { name: "Linzi", short: "portrait" },
      ],
      recap: "On the eleventh evening the party crossed the Thorn Ford and made for the Lanternrest, where a crow keeps the gable and the lantern over the door has not been lit in seven years. Mira swore she heard floorboards inside. Cassian did not disagree.",
    },
    {
      id: "bone-kings",
      title: "The Bone Kings of Aelven",
      subtitle: "Chapter VI — Beneath the Drowned Cathedral",
      system: "D&D 5e",
      chapter: "VI",
      lastPlayed: "three weeks past",
      sessions: 27,
      region: "Aelven Reach",
      day: "Day 41 · winter",
      party: [
        { name: "Brand", short: "portrait" },
        { name: "Sera", short: "portrait" },
        { name: "Ord", short: "portrait" },
      ],
      recap: "Sera lit the brazier on the altar and the cathedral answered with bells none of you had heard struck. The doors closed. The water began to rise.",
    },
    {
      id: "lantern",
      title: "Songs for the Last Lantern",
      subtitle: "Prelude",
      system: "Free Form",
      chapter: "0",
      lastPlayed: "last spring",
      sessions: 2,
      region: "The Greylands",
      day: "Day 3",
      party: [
        { name: "Wren", short: "portrait" },
        { name: "Tor", short: "portrait" },
      ],
      recap: "The road south of Hollowfell is not on any map. You have made it three days of walking. The last lantern, you are told, knows it is the last.",
    },
  ],

  party: [
    {
      id: "cassian",
      name: "Cassian Frostbreaker",
      short: "portrait",
      race: "Human",
      class: "Magus",
      archetype: "Eldritch Scion",
      alignment: "Neutral Good",
      level: 3,
      xp: 3880, xpMax: 5000,
      hp: 24, hpMax: 24,
      stats: {
        str: 16, dex: 12, con: 12, int: 10, wis: 8, cha: 19,
        ac: 17, flat: 16, touch: 13,
        fort: 6, reflex: 4, will: 4,
        bab: 2, melee: 5, ranged: 3, cmb: 5, cmd: 18,
        initiative: 1, speed: 30,
      },
      equipped: [
        { slot: "Head", name: "Hood of Embers", glyph: "hood" },
        { slot: "Body", name: "Studded leather", glyph: "armor" },
        { slot: "Main", name: "Longsword +1", glyph: "longsword" },
        { slot: "Off",  name: "Bound focus", glyph: "focus" },
        { slot: "Boots", name: "Travel boots", glyph: "boots" },
        { slot: "Ring", name: "Ring of clarity", glyph: "ring" },
      ],
      abilities: [
        { name: "Extended Magic", glyph: "spell·extend", detail: "Once per day, double the duration of one magus spell." },
        { name: "Dragon Resistances", glyph: "resist·flame", detail: "Energy resistance 10 (fire). Hide tougher than it looks." },
        { name: "Mage Armor", glyph: "ward·mage", detail: "Sheath of force grants +4 AC for 1 hr/lvl." },
        { name: "Spellstrike", glyph: "spell·strike", detail: "Channel a touch spell through a melee weapon attack." },
      ],
      feats: [
        { name: "Weapon Focus (Longsword)", glyph: "swordfocus", detail: "+1 to attack rolls with longswords." },
        { name: "Combat Casting", glyph: "concentrate", detail: "+4 concentration when casting on the defensive." },
        { name: "Arcane Strike", glyph: "spellstrike", detail: "As a swift action, weapons gain +1 damage and become magic." },
      ],
      skills: [
        { name: "Athletics", mod: 3 }, { name: "Mobility", mod: 1 },
        { name: "Persuasion", mod: 12 }, { name: "Perception", mod: 5 },
        { name: "Knowledge (Arcana)", mod: 6 }, { name: "Stealth", mod: 4 },
        { name: "Knowledge (World)", mod: 0 }, { name: "Trickery", mod: 1 },
        { name: "Lore (Nature)", mod: -1 }, { name: "Use Magic Device", mod: 4 },
        { name: "Lore (Religion)", mod: -1 }, { name: "Spellcraft", mod: 6 },
      ],
      spells: [
        { level: 1, list: [
          { name: "Mage Armor", school: "Abj", time: "1 std", glyph: "armor·spell" },
          { name: "Magic Missile", school: "Evo", time: "1 std", glyph: "missile" },
          { name: "Shocking Grasp", school: "Evo", time: "1 std", glyph: "spark" },
          { name: "True Strike", school: "Div", time: "1 std", glyph: "eye" },
        ]},
        { level: 0, list: [
          { name: "Detect Magic", school: "Div", time: "1 std", glyph: "ward" },
          { name: "Light", school: "Evo", time: "1 std", glyph: "light" },
          { name: "Prestidigitation", school: "Univ", time: "1 std", glyph: "spark·sm" },
        ]},
      ],
      proficiencies: [
        "Simple Weapons", "Martial Weapons",
        "Longsword", "Rapier", "Greatsword",
        "Light Armor", "Buckler",
      ],
      classFeatures: [
        { name: "Spell Combat", detail: "Wield a weapon in one hand while casting with the other." },
        { name: "Magus Arcana", detail: "Choose one magus arcana at 3rd level and every 3 levels thereafter." },
      ],
      traits: [
        { name: "Cold-blooded", detail: "Hails from the Frostbreak peaks. Cold weather is no inconvenience." },
        { name: "Sworn", detail: "Bound by oath to the Road Wardens. May not draw a blade in their hall." },
      ],
      dr: { value: "None", energy: "Fire 10" },
      lineage: "Born to a stonemason and a hedge-witch in the high town of Frostbreak. Apprenticed to the Magus circle of Restov at twelve. Took up the longsword the morning after his teacher buried his."
    },
    {
      id: "mira",
      name: "Mira of the Inkstain",
      short: "portrait",
      race: "Halfling",
      class: "Bard",
      archetype: "Lorekeeper",
      alignment: "Chaotic Good",
      level: 3, xp: 3120, xpMax: 5000, hp: 18, hpMax: 22,
      stats: { str: 8, dex: 16, con: 12, int: 16, wis: 12, cha: 18, ac: 15, flat: 12, touch: 14, fort: 2, reflex: 6, will: 4, bab: 2, melee: 1, ranged: 5, cmb: 1, cmd: 14, initiative: 3, speed: 20 },
      equipped: [
        { slot: "Head", name: "Bandana", glyph: "hood" },
        { slot: "Body", name: "Studded leather", glyph: "armor" },
        { slot: "Main", name: "Rapier", glyph: "rapier" },
        { slot: "Off",  name: "Lute of Whispers", glyph: "lute" },
        { slot: "Boots", name: "Soft boots", glyph: "boots" },
        { slot: "Ring", name: "—", glyph: "" },
      ],
      abilities: [
        { name: "Inspire Courage", glyph: "song", detail: "All allies within 30 ft gain +1 morale on attacks and saves." },
        { name: "Cantrip Repertoire", glyph: "scroll", detail: "Knows every cantrip she has ever overheard sung." },
      ],
      feats: [
        { name: "Lingering Performance", glyph: "echo", detail: "Bardic performance lasts 2 rounds after stopping." },
      ],
      skills: [
        { name: "Persuasion", mod: 9 }, { name: "Perception", mod: 6 },
        { name: "Stealth", mod: 9 }, { name: "Trickery", mod: 7 },
        { name: "Knowledge (Lore)", mod: 11 }, { name: "Performance", mod: 12 },
        { name: "Knowledge (Arcana)", mod: 6 }, { name: "Use Magic Device", mod: 7 },
      ],
      spells: [
        { level: 1, list: [
          { name: "Charm Person", school: "Ench", time: "1 std", glyph: "heart" },
          { name: "Sleep", school: "Ench", time: "1 std", glyph: "moon" },
          { name: "Cure Light", school: "Conj", time: "1 std", glyph: "leaf" },
        ]},
        { level: 0, list: [
          { name: "Dancing Lights", school: "Evo", time: "1 std", glyph: "light·sm" },
          { name: "Mage Hand", school: "Tns", time: "1 std", glyph: "hand" },
          { name: "Ghost Sound", school: "Ill", time: "1 std", glyph: "echo·sm" },
        ]},
      ],
      proficiencies: ["Simple Weapons", "Rapier", "Light Armor"],
      classFeatures: [
        { name: "Versatile Performance", detail: "Use Performance ranks in place of certain skill checks." },
        { name: "Lorekeeper", detail: "Add half level to all Knowledge checks." },
      ],
      traits: [
        { name: "Footloose", detail: "+1 to initiative checks. Cannot sit still for council." },
        { name: "Memory of Names", detail: "Always recalls a name once heard, whether it was offered or not." },
      ],
      dr: { value: "None", energy: "None" },
      lineage: "Found, not born — the inkstain on her left hand is the only thing she has from before. Trained by the chronicler-monks of Pitax until they realised she was writing better songs than psalms."
    },
    {
      id: "vell",
      name: "Vell Iron-Shod",
      short: "portrait",
      race: "Dwarf",
      class: "Fighter",
      archetype: "Two-Handed",
      alignment: "Lawful Neutral",
      level: 3, xp: 3500, xpMax: 5000, hp: 28, hpMax: 30,
      stats: { str: 18, dex: 10, con: 16, int: 10, wis: 12, cha: 8, ac: 18, flat: 18, touch: 10, fort: 7, reflex: 1, will: 2, bab: 3, melee: 7, ranged: 3, cmb: 7, cmd: 17, initiative: 0, speed: 20 },
      equipped: [
        { slot: "Head", name: "Iron helm", glyph: "helm" },
        { slot: "Body", name: "Chainmail", glyph: "chain" },
        { slot: "Main", name: "Greataxe", glyph: "axe" },
        { slot: "Off",  name: "—", glyph: "" },
        { slot: "Boots", name: "Iron-shod boots", glyph: "boots" },
        { slot: "Ring", name: "Ring of stamina", glyph: "ring" },
      ],
      abilities: [
        { name: "Cleave", glyph: "cleave", detail: "When you fell a foe, take a free attack at an adjacent enemy." },
        { name: "Stonecunning", glyph: "rune", detail: "+2 Perception to notice unusual stonework." },
      ],
      feats: [
        { name: "Power Attack", glyph: "smash", detail: "Trade attack accuracy for crushing damage." },
        { name: "Weapon Focus (Greataxe)", glyph: "axefocus", detail: "+1 to attack rolls with greataxes." },
      ],
      skills: [
        { name: "Athletics", mod: 9 }, { name: "Perception", mod: 5 },
        { name: "Intimidate", mod: 5 }, { name: "Mobility", mod: 0 },
        { name: "Survival", mod: 6 }, { name: "Knowledge (Engineering)", mod: 4 },
      ],
      spells: [],
      proficiencies: ["All Simple", "All Martial", "Heavy Armor", "Shields"],
      classFeatures: [
        { name: "Bravery", detail: "+1 to Will saves against fear." },
        { name: "Armor Training", detail: "Reduce armor check penalty by 1." },
      ],
      traits: [
        { name: "Sworn-Hammer", detail: "Once swore the Sworn-Hammer oath. Has not yet broken it." },
        { name: "Iron Liver", detail: "Cannot be poisoned by mortal drink." },
      ],
      dr: { value: "1/—", energy: "None" },
      lineage: "Of the Iron-Shod clan of the Five Kings. Left after a disagreement involving a hammer, a magistrate, and an unanswered question."
    },
  ],

  stash: [
    { id: "i1", name: "Iron rations", type: "common", glyph: "iron rations", qty: 6, weight: "6 lb", value: "18 gp", desc: "Six days of hard road food. Required for a safe rest outside town.", properties: ["consumable"], slot: "Pack" },
    { id: "i2", name: "Lanternrest key", type: "quest", glyph: "brass key", qty: 1, weight: "—", value: "story", desc: "Warm brass key with an inn mark scratched away.", origin: "Lanternrest", properties: ["bound"], lore: "It is warm, and should not be." },
    { id: "i3", name: "Ward chalk", type: "spell", glyph: "white chalk", qty: 1, weight: "1 lb", value: "44 gp", desc: "Lets the magus sketch a one-room detection ward before resting.", properties: ["1 use"] },
    { id: "i4", name: "Broken arrow", type: "rare", glyph: "broken arrow", qty: 1, weight: "1 lb", value: "75 gp", desc: "A relic from the first Road Warden company. Mira thinks it points to a buried oath.", origin: "Lanternrest cellar", lore: "This item once belonged to an ancient Brevan. It may be of interest to an antiquities expert.", loreBy: "Linzi, scribe", properties: ["relic"] },
    { id: "i5", name: "Blue candle", type: "spell", glyph: "blue wax candle", qty: 2, weight: "0.5 lb", value: "30 gp", desc: "Burns only when a pact is being violated nearby.", properties: ["alchemical"] },
    { id: "i6", name: "Odrun toll writ", type: "quest", glyph: "stamped scroll", qty: 1, weight: "—", value: "access", desc: "A stamped writ that can open one minor gate if the seal is not questioned." },
    { id: "i7", name: "Shield oil", type: "common", glyph: "small flask", qty: 3, weight: "2 lb", value: "9 gp", desc: "One camp use. Adds polish and removes rust from road rain." },
    { id: "i8", name: "Fate die", type: "rare", glyph: "bone die", qty: 3, weight: "—", value: "table", desc: "Spend to ask the chronicle for a dramatic complication instead of a simple failure.", properties: ["table"] },
    { id: "i9", name: "Travel cloak", type: "armor", glyph: "wool cloak", qty: 1, weight: "3 lb", value: "12 gp", desc: "Weatherproof cloak with a torn Odrun lining.", slot: "Body" },
    { id: "i10", name: "Salt charm", type: "rare", glyph: "salt charm", qty: 1, weight: "—", value: "50 gp", desc: "Protects one camp watch from dream intrusion.", properties: ["1 use"] },
    { id: "i11", name: "Ink map", type: "quest", glyph: "folded map", qty: 1, weight: "—", value: "story", desc: "Map of the Lanternrest cellars. The east room is drawn twice." },
    { id: "i12", name: "Focus shard", type: "spell", glyph: "crystal shard", qty: 1, weight: "0.2 lb", value: "38 gp", desc: "Improves one detect magic roll if crushed.", properties: ["1 use"] },
    { id: "i13", name: "Longsword", type: "weapon", glyph: "longsword", qty: 1, weight: "4 lb", value: "15 gp", desc: "A reliable infantry blade. Slightly chipped near the cross-guard.", slot: "Main" },
    { id: "i14", name: "Hunting bow", type: "weapon", glyph: "shortbow", qty: 1, weight: "2 lb", value: "30 gp", desc: "Mira's, originally. Vell has it now and Mira pretends not to mind.", slot: "Main" },
    { id: "i15", name: "Iron helm", type: "armor", glyph: "iron helm", qty: 1, weight: "5 lb", value: "20 gp", desc: "Standard issue infantry helm with dents that are not its own.", slot: "Head" },
    { id: "i16", name: "Mage hood", type: "armor", glyph: "wool hood", qty: 1, weight: "1 lb", value: "10 gp", desc: "Embroidered along the inside with a script you cannot read.", slot: "Head" },
    { id: "i17", name: "Healing draught", type: "spell", glyph: "red potion", qty: 4, weight: "0.5 lb", value: "50 gp", desc: "Restores 2d4+2 HP when consumed.", properties: ["1 use"] },
    { id: "i18", name: "Antitoxin", type: "spell", glyph: "green vial", qty: 1, weight: "0.5 lb", value: "50 gp", desc: "+5 alchemical to saves vs. poison for 1 hour.", properties: ["1 use"] },
    { id: "i19", name: "Lockpicks", type: "common", glyph: "thieves' tools", qty: 1, weight: "1 lb", value: "30 gp", desc: "Mira's set. The thinnest pick has been replaced twice." },
    { id: "i20", name: "Bedroll", type: "common", glyph: "bedroll", qty: 4, weight: "5 lb", value: "1 sp", desc: "Required for a long rest outside an inn." },
    { id: "i21", name: "Tinderbox", type: "common", glyph: "tinderbox", qty: 1, weight: "1 lb", value: "5 sp", desc: "Iron, flint, and a strip of dried fungus that smells faintly of myrrh." },
    { id: "i22", name: "Hill cheese", type: "common", glyph: "wheel of cheese", qty: 1, weight: "2 lb", value: "8 sp", desc: "Heavy, hard, lasts forever. Vell prefers it to most company." },
  ],

  quests: [
    {
      id: "q1",
      title: "The Lanternrest",
      label: "Active",
      tone: "crimson",
      status: "active",
      region: "Outskirts of Odrun",
      dateOpened: "9 Gozran",
      objective: "Investigate the still inn before the party reaches Odrun Fell.",
      entry: "Eleven days east of Restov the Lanternrest sits a hundred yards off the post-road, exactly where the post-roads pretend it isn't. The lantern over the door has not been lit in seven years. The roof is sound. The door is closed but the door is not locked. Cassian thinks this is the part to be afraid of.",
      entries: [
        { date: "12 Gozran, dusk", text: "Mira swears she heard a floorboard inside. Vell agrees it is the kind of building floorboards happen in. We will sleep in the courtyard. Whatever is inside has the night to make itself known." },
        { date: "12 Gozran, third watch", text: "The crow on the gable did not move. Not once. Not when Linzi threw a pebble that should have flushed it." },
      ],
      sketch: "the inn at dusk, crow on the gable",
      objectives: [
        { text: "Reach the Lanternrest courtyard.", done: true, note: "Arrived at dusk on the 12th." },
        { text: "Speak with whomever the inn keeps.", done: false },
        { text: "Discover what is in the east cellar.", done: false, note: "The map is drawn twice. Linzi is bothered by this." },
        { text: "Survive the night.", done: false },
      ],
      npcs: [
        { name: "The Crow", role: "watcher · unmoving", short: "raven" },
        { name: "Linzi", role: "scribe · party", short: "portrait" },
      ],
      reward: "1200 XP · 1 relic claim",
    },
    {
      id: "q2",
      title: "Gate of Tines",
      label: "Active",
      tone: "",
      status: "active",
      region: "Odrun Fell",
      dateOpened: "5 Gozran",
      objective: "Find why the city gate is sealed and who controls the toll road.",
      entry: "The gate of Tines has not opened to a caravan in two months. The toll-keeper of the south road took our writ, looked at it for longer than was polite, then handed it back without a stamp. He said the seal was correct. He did not say what the problem was.",
      entries: [],
      sketch: "the gate of tines, sealed",
      objectives: [
        { text: "Speak with the toll-keeper a second time.", done: false },
        { text: "Find an alternate path through the fell.", done: false },
      ],
      npcs: [
        { name: "Toll-keeper Olwen", role: "south gate · uneasy", short: "portrait" },
      ],
      reward: "850 XP",
    },
    {
      id: "q3",
      title: "Debt of the Shrine",
      label: "Active",
      tone: "",
      status: "active",
      region: "Thorn River",
      dateOpened: "2 Gozran",
      objective: "The road shrine wants a vow, a coin, or a remembered name.",
      entry: "The shrine on the Thorn Road has stood since before the maps were drawn. It asks for one of three. Vell offered a coin. Vell would. The shrine did not refuse but did not seem satisfied. Mira wants to come back with a name.",
      objectives: [
        { text: "Decide what the shrine is owed.", done: false },
        { text: "Return to the shrine before the next new moon.", done: false },
      ],
      npcs: [{ name: "The Shrine", role: "older than the road", short: "stone" }],
      reward: "1 boon · DM's discretion",
    },
    {
      id: "q4",
      title: "The Ferryman's Tab",
      label: "Resolved",
      tone: "emerald",
      status: "complete",
      region: "Restov Crossing",
      dateOpened: "27 Pharast",
      objective: "Settle the ferryman's tab before leaving Restov.",
      entry: "Three silver. Vell tried to pay in copper, which the ferryman declined as a matter of principle. We are square. We will not be ferried again, but we are square.",
      objectives: [{ text: "Pay the ferryman.", done: true }],
      npcs: [],
      reward: "200 XP",
    },
    {
      id: "q5",
      title: "Whispers at the Saltwell",
      label: "Rumor",
      tone: "",
      status: "rumor",
      region: "Whitebridge",
      dateOpened: "—",
      objective: "Travellers from Whitebridge mention something singing in the saltwell at dusk.",
      entry: "Heard third-hand at three different inns. Songs sung in a language nobody in Whitebridge speaks. The miller's daughter is missing. Or the miller never had a daughter. The accounts vary.",
      objectives: [{ text: "Visit Whitebridge.", done: false }],
      npcs: [],
      reward: "—",
    },
  ],

  locations: [
    { id: "lanternrest", name: "Lanternrest", x: 32, y: 240, region: "Outskirts of Odrun", distance: "0 leagues", travel: "you are here", current: true, discovered: true, visited: true,
      description: "An inn that should not still be standing. The lantern above the door has not been lit in seven years. The crow on the gable has not moved in three.",
      tags: ["mystery", "rest", "danger"], short: "inn at dusk", connections: ["thornford", "olegs"] },
    { id: "thornford", name: "Thorn Ford", x: 50, y: 280, region: "Thorn River", distance: "1 league", travel: "half a day on foot", discovered: true, visited: true,
      description: "A river crossing too shallow for a ferry, too deep for cartwheels in flood. Worn boots and patient feet.", tags: ["road"], short: "ford at dawn", connections: ["lanternrest", "templeoftheelk"] },
    { id: "olegs", name: "Oleg's Trading Post", x: 75, y: 120, region: "North Outskirts", distance: "3 leagues", travel: "two days, by road", discovered: true, visited: true,
      description: "A trading post hard against the cliff. Oleg's, by name and by temperament. The eastern wall has more spear-marks than the others.", tags: ["rest", "trade"], short: "trading post", connections: ["lanternrest", "oaks"] },
    { id: "templeoftheelk", name: "Temple of the Elk", x: 35, y: 420, region: "Stagwood", distance: "4 leagues", travel: "three days", discovered: true, visited: false,
      description: "A shrine to the Elk-That-Was. The antlers are tied to the roof with red wool. The wool is new. The antlers are not.", tags: ["holy"], short: "antlered shrine", connections: ["thornford", "abandonedhut"] },
    { id: "oaks", name: "Oak-That-Strayed", x: 50, y: 80, region: "Borderwood", distance: "5 leagues", travel: "three days", discovered: true, visited: false,
      description: "A single oak in a field that should be forest. The locals say it walked there. The locals also say not to ask whose oak it was.", tags: ["mystery"], short: "lone oak", connections: ["olegs", "abandonedhut"] },
    { id: "abandonedhut", name: "Abandoned Hut", x: 20, y: 200, region: "Thorn River", distance: "1.5 leagues", travel: "a day", discovered: true, visited: true,
      description: "A trapper's hut, abandoned. The fire-pit is still warm. It has been warm every time we have visited.", tags: ["mystery"], short: "hut in clearing", connections: ["templeoftheelk", "oaks"] },
    { id: "anciemtomb", name: "Ancient Tomb", x: 88, y: 380, region: "Old Hills", distance: "6 leagues", travel: "four days", discovered: true, visited: false,
      description: "A barrow with the door long broken. The wind that comes out of it does not match the wind outside.", tags: ["danger"], short: "open barrow", connections: ["thornford"] },
    { id: "techleague", name: "Technic League Camp", x: 45, y: 510, region: "Stagwood", distance: "7 leagues", travel: "five days", discovered: false, visited: false,
      description: "Reported, not yet seen. The smoke is the wrong colour.", tags: ["danger"], short: "smoke, wrong color", connections: ["templeoftheelk"] },
  ],

  tableLog: [
    { kind: "narration", text: "Day twelve. The road to Odrun has been quiet since the ford, and quiet is the sort of thing Vell stops trusting after the second hour. You make the Lanternrest at the failing of the light. The lantern above the door is, as promised, unlit. The crow on the gable is, as promised, present." },
    { kind: "action", who: "Mira", text: "approaches the door, palm flat against the wood, listening." },
    { kind: "roll", who: "Mira", text: "rolls d20: 17 + 6 Perception = 23" },
    { kind: "narration", text: "She hears, very faintly, the shifting of someone's weight on a wooden floor. Not approaching. Not retreating. Holding still, the way you hold still when you do not want to be heard. She steps back from the door without taking her eyes from it." },
    { kind: "dialog", who: "Mira", text: "There's someone in there. They know we know." },
    { kind: "action", who: "Cassian", text: "lights the brazier in the courtyard. Slowly." },
  ],
};

window.INITIAL_STATE = INITIAL_STATE;
